In [ ]:
summ=0
for num in range(1,9999999):
    summ +=num
summ

In [ ]:
summ=0
for num in range(1,9999999):
    summ +=num**2
summ

In [ ]:
summ=[]
for num in range(1, 1000000):
    summ.append(num**8)
summ


In [ ]:
import numpy as np


In [ ]:
array = np.arange(1,1000000,dtype=np.int64)**8 # insted of built-in data structer we use numpy because there use broadcasting and vectorization mothod 
array                                            # 1 & 1000000 are treat as vector

# ceration of arrays

In [ ]:
# convert a list into a array
arr=np.array([1,2,3,4,5,6]) # here the list convert into a array by np.array()
arr

In [ ]:
arr**2 # c=because of broadcasting and vectorization we can easily squred this array without looping

In [ ]:
# convert a tuple into a array
arr=np.array((1,2,3,4,5,6)) # here the tuple convert into a array by np.array()
arr

In [ ]:
arr.dtype #return data type here dtype('int32')

In [ ]:
arr1=np.array((1,2,3,4,5,6), dtype=np.int32) #converting data type int32 to int64
arr1.dtype
arr1.itemsize

In [ ]:
arr11=np.array((1,2,3,4,5,6), dtype=np.float64) #converting data type int32 to int64
arr1
arr1.dtype
arr11.itemsize

In [ ]:
arr1.ndim # return dimention

In [ ]:
arr1.size # return the number of element inside array size

In [ ]:
# convert a tuple into a array
arr=np.array((1,2,3,4,5,6)) # here the tuple convert into a array by np.array()
arr

In [ ]:
arr2=np.arange(20,2000,2,dtype=np.int64)
arr2

In [ ]:
arr2.shape # return number of values
arr2.size # return number of values


In [ ]:
# create expected elements 
# syntex: linespace(start, stop, expected elements)
arr3=np.linspace(20, 2000, 20000) # sequentiully return expected values 
arr3

In [ ]:
arr3.shape

In [ ]:
np.random.random(2000) # create random number

In [ ]:
np.random.randint(20, 2000) # return a single random int number between 20-2000

In [ ]:
arr4=np.random.randn(3,2) # return random values according to dimention
arr4

In [ ]:
arr4.ndim # return dimention

In [ ]:
arr5=np.random.randn(3,2,3) # return 3 dimentional random values according to dimention
arr5

In [ ]:
arr5.ndim
arr.itemsize # return index size, here each number consume 8 byte memory

# instant array generation

In [ ]:
# # matrix creating
m=np.zeros([2,2]) # row a7 col size alway remain into list / touple 
m

In [ ]:
m.ndim

In [ ]:
m1=np.ones((3,3)) # generating matrix
m1

In [48]:
m2=np.empty([3,2]) #generating matrix
m2

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [51]:
m4=np.eye(3,3) # generating identity matrix, here 1 lies diagnally
m4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
m4=np.eye(3,3,k=1) # here indexing shift 1 step right size 
m4

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
m5=np.eye(3,3,k=-1) # here indexing shift 1 step left size 
m5

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [58]:
m6=np.full([3,3], 5) # here we can fill matrix values in customize way
m6

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

# Array Dtypes

In [59]:
np.arange(1,20) # arange() generate int elements (by defolt)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [60]:
np.arange(1,20, dtype=np.float64)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19.])

In [61]:
np.arange(1,20, dtype=np.complex64) # generating complex number

array([ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,  7.+0.j,
        8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j, 14.+0.j,
       15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j], dtype=complex64)

In [65]:
np.array([True, False, True, True, False], dtype=np.bool8) #generating boolian data

array([ True, False,  True,  True, False])

In [66]:
#generating boolian data
np.array([True, False, True, True, 1,0,22], dtype=np.bool8) #here zero treat as False and other one 

array([ True, False,  True,  True,  True, False,  True])

In [69]:
np.array(['Apple','mango','orange'], dtype=np.string_) #generating string data type

array([b'Apple', b'mango', b'orange'], dtype='|S6')

# sicing

In [76]:
# generating customize matrix
arr6=np.array(

    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [79]:
arr6 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
arr6[0] # return first row

array([1, 2, 3])

In [85]:
arr6[0][1] # return first row's 2nd value
arr6[0,1] #same 

2

In [ ]:
arr6[0:2:1, ]