NumPy website
https://numpy.org/doc/stable/

In [ ]:
summ=0
for num in range(1,9999999):
    summ +=num
summ

In [ ]:
summ=0
for num in range(1,9999999):
    summ +=num**2
summ

In [ ]:
summ=[]
for num in range(1, 1000000):
    summ.append(num**8)
summ


In [5]:
import numpy as np


In [ ]:
array = np.arange(1,1000000,dtype=np.int64)**8 # insted of built-in data structer we use numpy because there use broadcasting and vectorization mothod 
array                                            # 1 & 1000000 are treat as vector

# ceration of arrays

In [ ]:
# convert a list into a array
arr=np.array([1,2,3,4,5,6]) # here the list convert into a array by np.array()
arr

In [ ]:
arr**2 # c=because of broadcasting and vectorization we can easily squred this array without looping

In [ ]:
# convert a tuple into a array
arr=np.array((1,2,3,4,5,6)) # here the tuple convert into a array by np.array()
arr

In [ ]:
arr.dtype #return data type here dtype('int32')

In [6]:
arr1=np.array((1,2,3,4,5,6), dtype=np.int32) #converting data type int32 to int64
arr1.dtype
arr1.itemsize

4

In [7]:
arr11=np.array((1,2,3,4,5,6), dtype=np.float64) #converting data type int32 to int64
arr1
arr1.dtype
arr11.itemsize

8

In [8]:
arr1.ndim # return dimention

1

In [ ]:
arr1.size # return the number of element inside array size

In [ ]:
# convert a tuple into a array
arr=np.array((1,2,3,4,5,6)) # here the tuple convert into a array by np.array()
arr

In [ ]:
arr2=np.arange(20,2000,2,dtype=np.int64)
arr2

In [ ]:
arr2.shape # return number of values
arr2.size # return number of values


In [9]:
# create expected elements 
# syntex: linespace(start, stop, expected elements)
arr3=np.linspace(20, 2000, 20000) # sequentiully return expected values 
arr3

array([  20.        ,   20.09900495,   20.1980099 , ..., 1999.8019901 ,
       1999.90099505, 2000.        ])

In [ ]:
arr3.shape

In [10]:
np.random.random(2000) # create random number

array([0.90781425, 0.88187293, 0.63762447, ..., 0.50939065, 0.78703841,
       0.68707991])

In [11]:
np.random.randint(20, 2000) # return a single random int number between 20-2000

575

In [12]:
arr4=np.random.randn(3,2) # return random values according to dimention
arr4

array([[-0.76929087,  0.88371881],
       [ 0.78191928,  0.34405539],
       [-1.32223572,  1.15078792]])

In [ ]:
arr4.ndim # return dimention

In [13]:
arr5=np.random.randn(3,2,3) # return 3 dimentional random values according to dimention
arr5

array([[[-1.18090799,  0.24910347,  0.11984587],
        [-0.1420151 ,  0.01537999,  1.47266571]],

       [[ 1.99467673, -0.24288397,  1.44378329],
        [ 0.18896026, -0.01463011,  0.91116125]],

       [[ 0.71190062,  2.00752775, -1.11233811],
        [-2.18640816,  1.10342593, -1.12376634]]])

In [14]:
arr5.ndim
arr.itemsize # return index size, here each number consume 8 byte memory

NameError: name 'arr' is not defined

# instant array generation

In [ ]:
# # matrix creating
m=np.zeros([2,2]) # row a7 col size alway remain into list / touple 
m

In [ ]:
m.ndim

In [ ]:
m1=np.ones((3,3)) # generating matrix
m1

In [ ]:
m2=np.empty([3,2]) #generating matrix
m2

In [ ]:
m4=np.eye(3,3) # generating identity matrix, here 1 lies diagnally
m4

In [ ]:
m4=np.eye(3,3,k=1) # here indexing shift 1 step right size 
m4

In [ ]:
m5=np.eye(3,3,k=-1) # here indexing shift 1 step left size 
m5

In [ ]:
m6=np.full([3,3], 5) # here we can fill matrix values in customize way
m6

# Array Dtypes

In [ ]:
np.arange(1,20) # arange() generate int elements (by defolt)

In [ ]:
np.arange(1,20, dtype=np.float64)

In [ ]:
np.arange(1,20, dtype=np.complex64) # generating complex number

In [ ]:
np.array([True, False, True, True, False], dtype=np.bool8) #generating boolian data

In [ ]:
#generating boolian data
np.array([True, False, True, True, 1,0,22], dtype=np.bool8) #here zero treat as False and other one 

In [ ]:
np.array(['Apple','mango','orange'], dtype=np.string_) #generating string data type

# Slicing

In [ ]:
# generating customize matrix
arr6=np.array(

    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [ ]:
arr6 

In [ ]:
arr6[0] # return first row

In [ ]:
arr6[0][1] # return first row's 2nd value
arr6[0,1] #same 

In [ ]:
#    rows    column
arr6[0:2:1,  1:3:1] # its will be increase upto n dimentions

In [ ]:
# 3 dimention
d=np.random.randn(3,3,3)
d

In [ ]:
d[0] # return first row's values

In [ ]:
d[0][1] #return first roew's 2nd column's values

In [ ]:
d[0][1][1] #return 1st row's 2nd column's 2nd index values

#  Filter

In [15]:
ar=np.arange(5,25)
ar

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [16]:
ar>10

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [ ]:
ar[ar>10]

In [ ]:
ar[(ar>10) & (ar<20)] # and operation

In [ ]:
ar[(ar<5) | (ar>20)] # or operation

In [ ]:
ar[~(ar>10)] # not operation

# Scaler

In [ ]:
# generating customize matrix
arr7=np.array(

    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [ ]:
arr7

In [ ]:
arr7[arr7>4]

In [ ]:
#adding
arr7+4
np.add(arr7,4) # both are similar

In [ ]:
#sqired
arr7**2
np.power(arr7,2) # both are similar

In [ ]:
# subtracting
arr7-2 
np.subtract(arr7, 2) # similar

In [ ]:
# multiply
arr7*3 
np.multiply(arr7,3) # similar

In [ ]:
# division
arr7/4
np.divide(arr7,4)

In [ ]:

#reminder
arr7%3, np.mod(arr7,3)  # both are similar

# matrix and vector operation

In [ ]:
x=np.eye(3,3)
x

In [ ]:
y=np.eye(3,3,k=1)
y

In [ ]:
# matrix addition
x+y

In [ ]:
a=np.array(

    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [ ]:
b=np.array(

    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [ ]:
# addition
a+b

In [ ]:
# multiplication
a*b

In [ ]:
#power
a**b

In [ ]:
# subtract
a-b

In [ ]:
# division
a/b

In [ ]:
# matrix multiplication
a@b
np.matmul(a,b) # similar

# statistics


In [ ]:
# adding matrix all values
a.sum()

In [ ]:
# row wise sum
a.sum(axis=1)

In [ ]:
# column wise sum
a.sum(axis=0)

In [ ]:
# mean of all values of matrix a
a.mean()

In [ ]:
a.mean(axis=1) # row wise mean

In [ ]:
a.mean(axis=0) # column wise mean

In [ ]:
# standard deviasion
a.std()

In [ ]:
a.std(axis=1) # row wise std

In [ ]:
a.std(axis=0) # column wise std

In [ ]:
# varience
a.var() 

In [ ]:
a.var(axis=1) # row wise varience

In [ ]:
a.var(axis=0) # column wise variance

In [ ]:
# return max value
a.max()

In [ ]:
# return min value
a.min()

In [ ]:
# return value diagonaly
a.diagonal()

In [ ]:
# copy this matrix
p=a.copy()
p

In [ ]:
# transpose this matrix
a.transpose()
a.T # similar

In [ ]:
# return the index number of minimum values
a.argmin()

In [ ]:
# return the index number of maximum values
a.argmax()

In [ ]:
# return median
np.median(a)

In [ ]:
# return median row wise
np.median(a,axis=1)

In [ ]:
# return median column wise
np.median(a,axis=0)

In [ ]:
# return covariance of 1st row & column
np.cov(a[0],b[0])

In [ ]:
#Covariance calculation
  # x  y
# x 1  1
# y 1  1

In [ ]:
np.cov([3,4,5,6],[3,5,7,4])

# Shaping

In [ ]:
arra=np.arange(1,21)
arra

In [ ]:
arra.reshape(10,2)

In [ ]:
arra.reshape(5,4)

In [114]:
n_arr=arra.reshape(5,4)
n_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
#return previous one 
n_arr.flatten()

In [ ]:
n_arr.reshape(20,1)

In [ ]:
# 3 dimentional 
p.reshape(2,5,2)

# Save NumPy data

In [115]:
np.save('array',n_arr) # Save an array to a binary file in NumPy

In [117]:
np.savetxt('array',n_arr) #Save an array to a text file.

# loading data from Numpy file

In [116]:
np.load('array.npy') # Load arrays or pickled objects from .npy, .npz or pickled files.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [118]:
np.loadtxt('array') #Load data from a text file.



array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.]])