In [ ]:
summ=0
for num in range(1,9999999):
    summ +=num
summ

In [ ]:
summ=0
for num in range(1,9999999):
    summ +=num**2
summ

In [ ]:
summ=[]
for num in range(1, 1000000):
    summ.append(num**8)
summ


In [ ]:
import numpy as np


In [ ]:
array = np.arange(1,1000000,dtype=np.int64)**8 # insted of built-in data structer we use numpy because there use broadcasting and vectorization mothod 
array                                            # 1 & 1000000 are treat as vector

# ceration of arrays

In [ ]:
# convert a list into a array
arr=np.array([1,2,3,4,5,6]) # here the list convert into a array by np.array()
arr

In [ ]:
arr**2 # c=because of broadcasting and vectorization we can easily squred this array without looping

In [ ]:
# convert a tuple into a array
arr=np.array((1,2,3,4,5,6)) # here the tuple convert into a array by np.array()
arr

In [ ]:
arr.dtype #return data type here dtype('int32')

In [ ]:
arr1=np.array((1,2,3,4,5,6), dtype=np.int32) #converting data type int32 to int64
arr1.dtype
arr1.itemsize

In [ ]:
arr11=np.array((1,2,3,4,5,6), dtype=np.float64) #converting data type int32 to int64
arr1
arr1.dtype
arr11.itemsize

In [ ]:
arr1.ndim # return dimention

In [ ]:
arr1.size # return the number of element inside array size

In [ ]:
# convert a tuple into a array
arr=np.array((1,2,3,4,5,6)) # here the tuple convert into a array by np.array()
arr

In [ ]:
arr2=np.arange(20,2000,2,dtype=np.int64)
arr2

In [ ]:
arr2.shape # return number of values
arr2.size # return number of values


In [ ]:
# create expected elements 
# syntex: linespace(start, stop, expected elements)
arr3=np.linspace(20, 2000, 20000) # sequentiully return expected values 
arr3

In [ ]:
arr3.shape

In [ ]:
np.random.random(2000) # create random number

In [ ]:
np.random.randint(20, 2000) # return a single random int number between 20-2000

In [ ]:
arr4=np.random.randn(3,2) # return random values according to dimention
arr4

In [ ]:
arr4.ndim # return dimention

In [ ]:
arr5=np.random.randn(3,2,3) # return 3 dimentional random values according to dimention
arr5

In [ ]:
arr5.ndim
arr.itemsize # return index size, here each number consume 8 byte memory

# instant array generation

In [ ]:
# # matrix creating
m=np.zeros([2,2]) # row a7 col size alway remain into list / touple 
m

In [ ]:
m.ndim

In [ ]:
m1=np.ones((3,3)) # generating matrix
m1

In [ ]:
m2=np.empty([3,2]) #generating matrix
m2

In [ ]:
m4=np.eye(3,3) # generating identity matrix, here 1 lies diagnally
m4

In [ ]:
m4=np.eye(3,3,k=1) # here indexing shift 1 step right size 
m4

In [ ]:
m5=np.eye(3,3,k=-1) # here indexing shift 1 step left size 
m5

In [ ]:
m6=np.full([3,3], 5) # here we can fill matrix values in customize way
m6

# Array Dtypes

In [ ]:
np.arange(1,20) # arange() generate int elements (by defolt)

In [ ]:
np.arange(1,20, dtype=np.float64)

In [ ]:
np.arange(1,20, dtype=np.complex64) # generating complex number

In [ ]:
np.array([True, False, True, True, False], dtype=np.bool8) #generating boolian data

In [ ]:
#generating boolian data
np.array([True, False, True, True, 1,0,22], dtype=np.bool8) #here zero treat as False and other one 

In [ ]:
np.array(['Apple','mango','orange'], dtype=np.string_) #generating string data type

# sicing

In [ ]:
# generating customize matrix
arr6=np.array(

    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [ ]:
arr6 

In [ ]:
arr6[0] # return first row

In [ ]:
arr6[0][1] # return first row's 2nd value
arr6[0,1] #same 

In [ ]:
#    rows    column
arr6[0:2:1,  1:3:1] # its will be increase upto n dimentions

In [ ]:
# 3 dimention
d=np.random.randn(3,3,3)
d

In [ ]:
d[0] # return first row's values

In [ ]:
d[0][1] #return first roew's 2nd column's values

In [ ]:
d[0][1][1] #return 1st row's 2nd column's 2nd index values

#  Filter

In [ ]:
ar=np.arange(5,25)
ar

In [ ]:
ar>10

In [ ]:
ar[ar>10]

In [ ]:
ar[(ar>10) & (ar<20)] # and operation

In [ ]:
ar[(ar<5) | (ar>20)] # or operation

In [ ]:
ar[~(ar>10)] # not operation

# Scaler

In [ ]:
# generating customize matrix
arr7=np.array(

    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [60]:
arr7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr7[arr7>4]

array([5, 6, 7, 8, 9])

In [64]:
#adding
arr7+4
np.add(arr7,4) # both are similar

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [65]:
#sqired
arr7**2
np.power(arr7,2) # both are similar

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [67]:
# subtracting
arr7-2 
np.subtract(arr7, 2) # similar

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [70]:
# multiply
arr7*3 
np.multiply(arr7,3) # similar

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [72]:
# division
arr7/4
np.divide(arr7,4)

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ],
       [1.75, 2.  , 2.25]])

In [74]:

#reminder
arr7%3, np.mod(arr7,3)  # both are similar

(array([[1, 2, 0],
        [1, 2, 0],
        [1, 2, 0]], dtype=int32),
 array([[1, 2, 0],
        [1, 2, 0],
        [1, 2, 0]], dtype=int32))

# matrix and vector operation

In [76]:
x=np.eye(3,3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
y=np.eye(3,3,k=1)
y

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [79]:
# matrix addition
x+y

array([[1., 1., 0.],
       [0., 1., 1.],
       [0., 0., 1.]])

In [81]:
a=np.array(

    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [82]:
b=np.array(

    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [83]:
# addition
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [84]:
# multiplication
a*b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [86]:
#power
a**b

array([[        1,         4,        27],
       [      256,      3125,     46656],
       [   823543,  16777216, 387420489]])

In [87]:
# subtract
a-b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [88]:
# division
a/b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [93]:
# matrix multiplication
a@b
np.matmul(a,b) # similar

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# statistics


In [94]:
# adding matrix all values
a.sum()

45

In [95]:
# row wise sum
a.sum(axis=1)

array([ 6, 15, 24])

In [97]:
# column wise sum
a.sum(axis=0)

array([12, 15, 18])

In [98]:
# mean of all values of matrix a
a.mean()

5.0

In [99]:
a.mean(axis=1) # row wise mean

array([2., 5., 8.])

In [100]:
a.mean(axis=0) # column wise mean

array([4., 5., 6.])

In [101]:
# standard deviasion
a.std()

2.581988897471611

In [104]:
a.std(axis=1) # row wise std

array([0.81649658, 0.81649658, 0.81649658])

In [102]:
a.std(axis=0) # column wise std

array([2.44948974, 2.44948974, 2.44948974])

In [107]:
# varience
a.var() 

6.666666666666667

In [108]:
a.var(axis=1) # row wise varience

array([0.66666667, 0.66666667, 0.66666667])

In [109]:
a.var(axis=0) # column wise variance

array([6., 6., 6.])

In [110]:
# return max value
a.max()

9

In [111]:
# return min value
a.min()

1

In [113]:
# return value diagonaly
a.diagonal()

array([1, 5, 9])

In [116]:
# copy this matrix
p=a.copy()
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
# transpose this matrix
a.transpose()
a.T # similar

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [124]:
# return the index number of minimum values
a.argmin()

0

In [126]:
# return the index number of maximum values
a.argmax()

8

In [127]:
# return median
np.median(a)

5.0

In [128]:
# return median row wise
np.median(a,axis=1)

array([2., 5., 8.])

In [129]:
# return median column wise
np.median(a,axis=0)

array([4., 5., 6.])

In [131]:
# return covariance of 1st row & column
np.cov(a[0],b[0])

array([[1., 1.],
       [1., 1.]])

In [ ]:
#Covariance calculation
  # x  y
# x 1  1
# y 1  1

SyntaxError: invalid syntax (1620432171.py, line 1)