In [ ]:
summ=0
for num in range(1,9999999):
    summ +=num
summ

In [ ]:
summ=0
for num in range(1,9999999):
    summ +=num**2
summ

In [ ]:
summ=[]
for num in range(1, 1000000):
    summ.append(num**8)
summ


In [ ]:
import numpy as np


In [ ]:
array = np.arange(1,1000000,dtype=np.int64)**8 # insted of built-in data structer we use numpy because there use broadcasting and vectorization mothod 
array                                            # 1 & 1000000 are treat as vector

# ceration of arrays

In [ ]:
# convert a list into a array
arr=np.array([1,2,3,4,5,6]) # here the list convert into a array by np.array()
arr

In [ ]:
arr**2 # c=because of broadcasting and vectorization we can easily squred this array without looping

In [ ]:
# convert a tuple into a array
arr=np.array((1,2,3,4,5,6)) # here the tuple convert into a array by np.array()
arr

In [ ]:
arr.dtype #return data type here dtype('int32')

In [ ]:
arr1=np.array((1,2,3,4,5,6), dtype=np.int32) #converting data type int32 to int64
arr1.dtype
arr1.itemsize

In [ ]:
arr11=np.array((1,2,3,4,5,6), dtype=np.float64) #converting data type int32 to int64
arr1
arr1.dtype
arr11.itemsize

In [ ]:
arr1.ndim # return dimention

In [ ]:
arr1.size # return the number of element inside array size

In [ ]:
# convert a tuple into a array
arr=np.array((1,2,3,4,5,6)) # here the tuple convert into a array by np.array()
arr

In [ ]:
arr2=np.arange(20,2000,2,dtype=np.int64)
arr2

In [ ]:
arr2.shape # return number of values
arr2.size # return number of values


In [ ]:
# create expected elements 
# syntex: linespace(start, stop, expected elements)
arr3=np.linspace(20, 2000, 20000) # sequentiully return expected values 
arr3

In [ ]:
arr3.shape

In [ ]:
np.random.random(2000) # create random number

In [ ]:
np.random.randint(20, 2000) # return a single random int number between 20-2000

In [ ]:
arr4=np.random.randn(3,2) # return random values according to dimention
arr4

In [ ]:
arr4.ndim # return dimention

In [ ]:
arr5=np.random.randn(3,2,3) # return 3 dimentional random values according to dimention
arr5

In [ ]:
arr5.ndim
arr.itemsize # return index size, here each number consume 8 byte memory

# instant array generation

In [ ]:
# # matrix creating
m=np.zeros([2,2]) # row a7 col size alway remain into list / touple 
m

In [ ]:
m.ndim

In [ ]:
m1=np.ones((3,3)) # generating matrix
m1

In [ ]:
m2=np.empty([3,2]) #generating matrix
m2

In [ ]:
m4=np.eye(3,3) # generating identity matrix, here 1 lies diagnally
m4

In [ ]:
m4=np.eye(3,3,k=1) # here indexing shift 1 step right size 
m4

In [ ]:
m5=np.eye(3,3,k=-1) # here indexing shift 1 step left size 
m5

In [ ]:
m6=np.full([3,3], 5) # here we can fill matrix values in customize way
m6

# Array Dtypes

In [ ]:
np.arange(1,20) # arange() generate int elements (by defolt)

In [ ]:
np.arange(1,20, dtype=np.float64)

In [ ]:
np.arange(1,20, dtype=np.complex64) # generating complex number

In [ ]:
np.array([True, False, True, True, False], dtype=np.bool8) #generating boolian data

In [ ]:
#generating boolian data
np.array([True, False, True, True, 1,0,22], dtype=np.bool8) #here zero treat as False and other one 

In [ ]:
np.array(['Apple','mango','orange'], dtype=np.string_) #generating string data type

# sicing

In [ ]:
# generating customize matrix
arr6=np.array(

    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [ ]:
arr6 

In [ ]:
arr6[0] # return first row

In [48]:
arr6[0][1] # return first row's 2nd value
arr6[0,1] #same 

2

In [53]:
#    rows    column
arr6[0:2:1,  1:3:1] # its will be increase upto n dimentions

array([[2, 3],
       [5, 6]])

In [56]:
# 3 dimention
d=np.random.randn(3,3,3)
d

array([[[-1.45926373, -1.38426591,  0.43622269],
        [-0.84447728, -0.47723603, -0.48913594],
        [ 1.11191284,  0.2044057 ,  2.93751572]],

       [[-0.22414861, -0.29158321, -0.49357684],
        [-0.56138479, -0.09938755,  2.11562976],
        [ 0.17086252,  0.32476223,  0.46184753]],

       [[ 0.01882064,  1.41386908,  1.69662999],
        [ 0.39290357,  1.41905188,  1.59685533],
        [-0.07143146,  1.14129309, -1.11070165]]])

In [59]:
d[0] # return first row's values

array([[-1.45926373, -1.38426591,  0.43622269],
       [-0.84447728, -0.47723603, -0.48913594],
       [ 1.11191284,  0.2044057 ,  2.93751572]])

In [62]:
d[0][1] #return first roew's 2nd column's values

array([-0.84447728, -0.47723603, -0.48913594])

In [64]:
d[0][1][1] #return 1st row's 2nd column's 2nd index values

-0.47723603406822923

#  Filter

In [79]:
ar=np.arange(5,25)
ar

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [80]:
ar>10

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [82]:
ar[ar>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [83]:
ar[(ar>10) & (ar<20)] # and operation

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [86]:
ar[(ar<5) | (ar>20)] # or operation

array([21, 22, 23, 24])

In [87]:
ar[~(ar>10)] # not operation

array([ 5,  6,  7,  8,  9, 10])