In [1]:
import numpy as np

# Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.


In [ ]:
import numpy as np

print(np.__version__)

# 1. Creating Arrays
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [ ]:
# Use a list to create a NumPy array:
arr = np.array([1, 2, 3, 4, 5]) 
print(arr)
print(type(arr))

In [ ]:
# Use a tuple to create a NumPy array:
arr = np.array((1, 2, 3, 4, 5))
print(arr)

# 2. Dimensions in Arrays

In [ ]:
# 0-D array
# Create a 0-D or Scalars array with value 42
arr = np.array(42)
print(arr)

In [ ]:
# 1-D array
# An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
# Create  uni-dimensional or 1-D array containing the values 1,2,3,4,5:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

In [ ]:
# 2-D Arrays
# An array that has 1-D arrays as its elements is called a 2-D array.
# These are often used to represent matrix or 2nd order tensors.
# Create a 2-D array containing two 1D arrays with the values 1,2,3 and 4,5,6:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

In [ ]:
# 3-D arrays
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.
# These are often used to represent a 3rd order tensor.
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

In [ ]:
#Check Number of Dimensions?
#NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

In [ ]:
# Higher Dimensional Arrays
# An array can have any number of dimensions.
#When the array is created, you can define the number of dimensions by using the ndmin argument.
#Create an array with 5 dimensions and verify that it has 5 dimensions:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

# 3. NumPy Array Indexing
Array indexing is the same as accessing an array element.
You can access an array element by referring to its index number.

In [ ]:
# Get the first element from the following array:
arr = np.array([1, 2, 3, 4])
print(arr[0])

In [ ]:
#Get third and fourth elements from the following array and add them.
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

In [ ]:
# Access 2-D Arrays
#Think of 2-D arrays like a table with rows and columns, 
# where the row represents the dimension and the index represents the column.
#Access the element on the first row, second column:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

In [ ]:
# Access 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1, 1, 1])

In [ ]:
# Negative Indexing
# Use negative indexing to access an array from the end.
# Print the last element from the 2nd dim:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

# 4. NumPy Array Slicing
Slicing in python means taking elements from one given index to another given index.
We pass slice instead of index like this: [start:end:step].

In [ ]:
# Slice elements from index 1 to index 5 from the following array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

In [ ]:
# Slice elements from index 4 to the end of the array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

In [ ]:
# Slice elements from the beginning to index 4 (not included):
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

In [ ]:
# Negative Slicing
# Slice from the index 3 from the end to index 1 from the end:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

In [ ]:
# STEP
# Return every other element from index 1 to index 5:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

In [ ]:
# STEP 
# Return every other element from the entire array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

In [ ]:
# Slicing 2-D Arrays
# From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

In [ ]:
# From both elements, return index 2:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

In [ ]:
# From both elements, slice index 1 to index 4 (not included), 
# this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

# 5. NumPy Data Types

In [ ]:
# NumPy array object has a property called dtype 
# that returns the data type of the array:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

In [ ]:
# Creating Arrays With a Defined Data Type
# For i, u, f, S and U we can define size as well.
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

In [ ]:
arr = np.array([1, 2, 3, 4],dtype='i8' )

print(arr)
print(arr.dtype)

In [ ]:
# Create an array with data type 4 bytes integer:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

In [ ]:
# Change data type from float to integer by using 'i' as parameter value: 
# using astype() method.
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

In [ ]:
# Change data type from float to integer by using int as parameter value:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

In [ ]:
# Change data type from integer to boolean:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

# 6. NumPy Array Copy vs View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

In [ ]:
#COPY:
# Make a copy, change the original array, and display both arrays:
# The copy SHOULD NOT be affected by the changes made to the original array.
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

In [ ]:
# VIEW:
# Make a view, change the original array, and display both arrays:
# The view SHOULD be affected by the changes made to the original array.
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

# 7. NumPy Array Shape
The shape of an array is the number of elements in each dimension.

In [ ]:
# Print the shape of a 1-D array:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.shape)

In [ ]:
# Print the shape of a 2-D array:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

In [ ]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and
# verify that last dimension has value 4:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

# 8. NumPy Array Reshaping
Reshaping means changing the shape of an array.
The shape of an array is the number of elements in each dimension.
By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [ ]:
# Reshape From 1-D to 2-D
# Convert the following 1-D array with 12 elements into a 2-D array.
#The outermost dimension will have 4 arrays, each with 3 elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

In [ ]:
# Reshape From 1-D to 3-D
# Convert the following 1-D array with 12 elements into a 3-D array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

In [ ]:
# Unknown Dimension
# You are allowed to have one "unknown" dimension.
# Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
# Pass -1 as the value, and NumPy will calculate this number for you.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

In [ ]:
# Flattening the arrays
# Flattening array means converting a multidimensional array into a 1D array.
# We can use reshape(-1) to do this.
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.

# 9. NumPy Array Iterating
Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

In [ ]:
# Iterating 1-D Arrays
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

In [ ]:
# Iterating 2-D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

In [ ]:
# Iterating 2-D Arrays
# Iterate on each scalar element of the 2-D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

In [ ]:
# Iterating 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

Iterating Arrays Using nditer()

In [ ]:
# Iterating 2-D Arrays Using nditer()
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in np.nditer(arr):
    print(x)

In [ ]:
# Iterating 3-D Arrays Using nditer()
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

In [ ]:
# Iterating Array With Different Data Types
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

Note: NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [ ]:
# Iterating With Different Step Size
arr = np.array([[1, 2, 3, 4,5, 6, 7, 8], [9,10,11,12,13,14,15,16]])
for x in np.nditer(arr[0:2, 2:6:3]):
  print(x)

Enumerated Iteration Using ndenumerate()

In [ ]:
# Enumerate on following 1D arrays elements:
arr = np.array([1, 2, 3,6,7,9])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

In [ ]:
# Enumerate on following 2D array's elements:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

In [ ]:
# Enumerate on following 2D array's elements:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

# 10 NumPy Joining Array
Joining means putting contents of two or more arrays in a single array.
In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.
We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [ ]:
# Joining two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2),axis=0)
print(arr)

In [ ]:
# Join two 2-D arrays along rows (axis=1):
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

In [ ]:
# Join two 3-D arrays along rows (axis=2):
arr1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr2 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
arr = np.concatenate((arr1, arr2,),axis=2)
print(arr)

Joining Arrays Using Stack Functions

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

In [ ]:
# np.stack()
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2),axis=0)
print(arr)

In [ ]:
# Stacking Along Rows
# NumPy provides a helper function: hstack() to stack along rows.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

In [ ]:
# Stacking Along Columns
# NumPy provides a helper function: vstack()  to stack along columns.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

In [ ]:
# Stacking Along Height (depth)
# NumPy provides a helper function: dstack() to stack along height, which is the same as depth.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

# 11. NumPy Splitting Array
Splitting is reverse operation of Joining.
The return value of the array_split() method is an array containing each of the split as an array.

In [ ]:
# Split the array in 3 parts:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

In [ ]:
# Split the array in 4 parts:
# If the array has less elements than required, 
# it will adjust from the end accordingly.
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])

In [ ]:
newarr[0][1]

In [ ]:
# Split the 2-D array into three 2-D arrays.
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

In [ ]:
# Split the 2-D array into three 2-D arrays along rows.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

In [ ]:
# hsplit()
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

In [95]:
# vsplit()
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.vsplit(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


# 12. NumPy Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.
To search an array, use the where() method.

In [8]:
# Find the indexes where the value is 4:
arr = np.array([1, 2, 3, 6, 4, 7,4])
x = np.where(arr == 4)
print(x)

(array([4, 6], dtype=int64),)


In [9]:
# Find the indexes where the values are even:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [10]:
# Find the indexes where the values are odd:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [12]:
arr = np.array([6, 7, 8,7, 9,7])

x = np.searchsorted(arr, 7)

print(x)

1


In [5]:
arr = np.array([1,3,5,6,4])
x = np.searchsorted(arr, [6, 4,8])
print(x)

[5 2 5]
